server:
  port: 8081

spring:
  application:
    name: users
  profiles:
    # 🚀 Si no se inyecta ninguna variable externa del sistema, activa el perfil 'dev' por defecto [1]
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}            