spring:
  config:
    activate:
      on-profile: prod
  datasource:
    # En producción se lee estrictamente de las variables de entorno del contenedor [1]
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    # ⚡ CONFIGURACIÓN HIKARI AGRESIVA PARA PRODUCCIÓN (ESTRÉS)
    hikari:
      pool-name: users-prd-hikari-pool
      # Mismo número en maximum y minimum precalienta todas las conexiones al arrancar
      # Evita la penalización de tiempo de crear conexiones bajo demanda en picos de tráfico
      maximum-pool-size: 20
      minimum-idle: 20
      # Reducimos el timeout a 15 segundos para fallar rápido (Fail-Fast) si la BD se satura
      connection-timeout: 15000
      # Control estricto de vida de conexiones para evitar fugas y "conexiones muertas"
      idle-timeout: 300000
      max-lifetime: 1200000
      # Query de validación rápida para asegurar que la conexión sigue viva antes de usarla
      connection-test-query: SELECT 1

    # Optimizamos reduciendo logs de proxy en producción, la telemetría va directo a Jaeger
    proxy:
      logging: warn
      query:
        enable-logging: true
        log-entry-creator: single-line

  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          # Desactiva los comentarios SQL pesados en consola para mejorar rendimiento
          use_sql_comments: false
          format_sql: false

management:     
  # 1. Configuración de Métricas (Mapeado bajo Micrometer OTLP)
  otlp:
    metrics:
      export:
        url: http://alloy:4318/v1/metrics
        step: 10s

  # 2. Configuración de Trazas y Logs (Mapeado bajo el Starter de OpenTelemetry)
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://alloy:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://alloy:4318/v1/logs

  # 3. Configuración del Motor de Rastreo General
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: [W3C]
      produce: [W3C]

api:
  products:
    # Apunta al nombre del contenedor o DNS interno en la red de producción de Docker [1]
    url: ${PRODUCTS_API_URL}/api/products
