# -------------------------------------------------------------------------
# 🐳 DOCKER COMPOSE - ENTORNO DE PRODUCCIÓN / INTEGRACIÓN GLOBAL
# - AUTOR: @DevSoft Team
# - DESCRIPCION: Levanta la infraestructura completa del ecosistema distribuido
# -              (2 Microservicios independientes + 2 Bases de Datos dedicadas)
# -------------------------------------------------------------------------

services:

  # =======================================================================
  # 📦 COMPONENTE 1: DOMINIO DE PRODUCTOS (API + BASE DE DATOS)
  # =======================================================================

  # 🐬 Servidor MySQL dedicado a Productos
  db_products:
    image: mysql:9.0
    container_name: prod_db_srv_products
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD_PRODUCTS}
      MYSQL_DATABASE: ${DB_NAME_PRODUCTS}
      MYSQL_USER: ${DB_USER_PRODUCTS}
      MYSQL_PASSWORD: ${DB_PASSWORD_PRODUCTS}
    ports:
      - "3310:3306"
    command: --lower_case_table_names=1
    volumes:
      - production_mysql_data_products:/var/lib/mysql
      - ../products/.devcontainer/mysql-products-schema-v1.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - ntw_production
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER_PRODUCTS:-products}", "-p${DB_PASSWORD_PRODUCTS:-products2026}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 🚀 Aplicación Java de Productos (Imagen compila con su Dockerfile)
  products-app:
    image: workshop/products-service:latest
    container_name: prod-app-products
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE_ENV}
      DB_HOSTNAME: ${DB_PRODUCTS_HOSTNAME}
      DB_PORT: ${DB_PRODUCTS_PORT}
      DB_NAME: ${DB_NAME_PRODUCTS}
      DB_USER: ${DB_USER_PRODUCTS}
      DB_PASSWORD: ${DB_PASSWORD_PRODUCTS}
      OTEL_SERVICE_NAME: products-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317 # Apunta al contenedor receptor por gRPC
    ports:
      - "8088:8080"
    networks:
      - ntw_production
    depends_on:
      db_products:
        condition: service_healthy

  # =======================================================================
  # 👥 COMPONENTE 2: DOMINIO DE USUARIOS (API + BASE DE DATOS)
  # =======================================================================

  # 🐬 Servidor MySQL dedicado a Usuarios
  db_users:
    image: mysql:9.0
    container_name: prod_db_srv_users
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD_USERS}
      MYSQL_DATABASE: ${DB_NAME_USERS}
      MYSQL_USER: ${DB_USER_USERS}
      MYSQL_PASSWORD: ${DB_PASSWORD_USERS}
    ports:
      - "3311:3306"
    volumes:
      - production_mysql_data_users:/var/lib/mysql
      - ../users/.devcontainer/mysql-users-schema-v1.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --lower_case_table_names=1
    networks:
      - ntw_production
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER_USERS}", "-p${DB_PASSWORD_USERS}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 🚀 Aplicación Java de Usuarios (Imagen compila con su Dockerfile)
  users-app:
    image: workshop/users-service:latest
    container_name: prod-app-users
    restart: always
    ports:
      - "8089:8081"
    environment:
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://alloy:4318/v1/traces
      SPRING_APPLICATION_NAME: users-service
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE_ENV} # 🚀 ACTIVA EL PERFIL DE PRODUCCIÓN
      PRODUCTS_API_URL: ${PRODUCTS_BASE_URL}
      DB_HOSTNAME: ${DB_USERS_HOSTNAME}
      DB_PORT: ${DB_USERS_PORT}
      DB_NAME: ${DB_NAME_USERS}
      DB_USER: ${DB_USER_USERS}
      DB_PASSWORD: ${DB_PASSWORD_USERS}
      OTEL_SERVICE_NAME: users-service
    volumes:
      - vlm_users_logs:/app/logs  
    networks:
      - ntw_production
    depends_on:
      db_users:
        condition: service_healthy
      products-app:
        condition: service_started

# =======================================================================
# 🌐 RED COMÚN EXTERNA Y VOLÚMENES PERSISTENTES
# =======================================================================
networks:
  ntw_production:
    name: ntw_production
    external: true

volumes:
  production_mysql_data_products:
  production_mysql_data_users:
  vlm_users_logs:
    external: true
      
