apiVersion: v1
kind: Secret
metadata:
  name: workshop-shared-secret
  namespace: workshop-k8s
type: Opaque
data:
  # 🔐 CONTRASEÑAS CODIFICADAS EN BASE64 (Texto plano: products2026 y users2026)
  DB_PASSWORD_PRODUCTS: cHJvZHVjdHMyMDI2
  DB_PASSWORD_USERS: dXNlcnMyMDI2
