apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-app
  namespace: workshop-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products-app
  template:
    metadata:
      labels:
        app: products-app
    spec:
      containers:
        - name: products-container
          image: wortiz1027/products-service:latest
          imagePullPolicy: IfNotPresent # 🐳 Si ya la compilaste en el nodo, la usa de inmediato
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: DB_NAME
              value: productsdb
            - name: DB_HOSTNAME
              value: "192.168.1.7"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: users
            - name: DB_PASSWORD
              value: users2026
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "180Mi"
              cpu: "150m"      # 🚀 Subimos al 15% de un núcleo para que logre arrancar
            limits:
              memory: "300Mi"  # Evita el OOMKilled
              cpu: "300m"
          #startupProbe:
          #  httpGet:
          #    path: /actuator/health # O la ruta de salud de tu API
          #    port: 8080
          #  failureThreshold: 12     # Lo intenta 12 veces...
          #  periodSeconds: 5         # ...cada 5 segundos (Dando 60 segundos totales de gracia)