apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: users-app-hpa
  namespace: workshop-k8s
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # 📈 Si la CPU supera el 50%, dispara un nuevo Pod
