spring:
  config:
    activate:
      on-profile: dev
  datasource:
      url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME:productsdb}?useSSL=false&serverTimezone=UTC&noAccessToProcedureBodies=false
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 🔧 CONFIGURACIÓN HIKARI PARA DESARROLLO
      hikari:
          pool-name: users-dev-hikari-pool
          # Empezamos con pocas conexiones para ahorrar memoria en local
          minimum-idle: 2
          maximum-pool-size: 5
          # Tiempo máximo que espera el código por una conexión antes de dar error (30 segundos)
          connection-timeout: 30000
          # Cuánto tiempo puede estar una conexión ociosa en el pool antes de cerrarse (10 minutos)
          idle-timeout: 600000
          max-lifetime: 1800000
      proxy:
        logging: info
        query:
          enable-logging: true
          log-entry-creator: single-line # Muestra la query en una sola línea compacta dentro de Jaeger        
  jpa:
      hibernate:
          ddl-auto: validate

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: W3C
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://jaeger:4318/v1/traces