server:
  port: 8000
  
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME:eureka-server}:${EUREKA_SERVER_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: products
              uri: lb://products # Balanceador dinámico apuntando al ID de Eureka
              predicates:
                - Path=/api/products/**

            - id: users-route
              uri: lb://users
              predicates:
                - Path=/api/users/**