server:
  port: 8761 # 🚀 Puerto estándar oficial de Eureka Server

spring:
  application:
    name: eureka-server
  config:
    # 🔌 Le indica a Eureka que busque sus propiedades reales en el Config Server
    import: "optional:configserver:http://${CONFIG_SERVER_HOSTNAME:config-server}:${CONFIG_SERVER_PORT:9999}"
  profiles:
    active: dev # Perfil por defecto para pruebas locales
