services:
  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: jaeger
    hostname: jaeger
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Puerto del Dashboard Visual de Jaeger
      - "4317:4317"   # Puerto receptor OTLP (gRPC) - Al que apuntarán las apps
      - "4318:4318" # OTLP HTTP
    volumes:  
      - ./configs/jaeger/jaeger.yaml:/etc/jaeger/jaeger.yaml
    networks:
      - ntw_cloud

  # =======================================================================
  # 🔐 SERVIDOR DE IDENTIDAD: KEYCLOAK (OAuth2 / OIDC Provider)
  # =======================================================================
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: cloud-keycloak-server
    restart: always
    command: start-dev # 🚀 Modo desarrollo: Habilita HTTP para pruebas locales del laboratorio
    ports:
      - "8082:8080" # Expone el puerto 8082 en tu máquina física para administrar la consola web
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    networks:
      - ntw_cloud
    volumes:
      - ./configs/keycloak/workshop-realm.json:/opt/keycloak/data/import/workshop-realm.json      
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080 && echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | grep -q '200 OK'"]
      interval: 10s
      timeout: 5s
      retries: 5

# =======================================================================
# 🌐 RED COMÚN EXTERNA Y VOLÚMENES PERSISTENTES
# =======================================================================
networks:
  ntw_cloud:
    name: ntw_cloud
    external: true