services:
  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: jaeger
    hostname: jaeger
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Puerto del Dashboard Visual de Jaeger
      - "4317:4317"   # Puerto receptor OTLP (gRPC) - Al que apuntarán las apps
      - "4318:4318" # OTLP HTTP
    volumes:  
      - ./configs/jaeger/jaeger.yaml:/etc/jaeger/jaeger.yaml
    networks:
      - ntw_cloud

# =======================================================================
# 🌐 RED COMÚN EXTERNA Y VOLÚMENES PERSISTENTES
# =======================================================================
networks:
  ntw_cloud:
    name: ntw_cloud
    external: true