SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- 1. CREACIÓN DEL ESQUEMA LOCAL DE USUARIOS
CREATE SCHEMA IF NOT EXISTS `usersdb` DEFAULT CHARACTER SET utf8 ;
USE `usersdb` ;

-- 2. CREACIÓN DE LA TABLA DE USUARIOS
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID    VARCHAR(512),
    USER_NAME  VARCHAR(512),
    USER_EMAIL VARCHAR(512),
    USER_ROLE  VARCHAR(128)
) ENGINE = InnoDB;

ALTER TABLE USERS ADD CONSTRAINT PK_USER PRIMARY KEY (USER_ID);

-- 3. TABLA DE RELACIÓN (Instancias de productos comprados)
CREATE TABLE IF NOT EXISTS USERS_PRODUCTS (
    RELATION_ID   VARCHAR(512),
    USER_ID       VARCHAR(512),
    PRODUCT_ID    VARCHAR(512), -- Se mantiene como String huérfano ya que apunta a otro servidor
    PURCHASE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB;

ALTER TABLE USERS_PRODUCTS ADD CONSTRAINT PK_USER_PROD PRIMARY KEY (RELATION_ID);
ALTER TABLE USERS_PRODUCTS ADD INDEX(USER_ID);

-- 🚀 AGREGAMOS LA LLAVE FORÁNEA LOCAL DE INTEGRIDAD
-- Si un usuario se elimina, se borran en cascada sus asignaciones de productos
ALTER TABLE USERS_PRODUCTS 
ADD CONSTRAINT FK_USERS_PRODUCTS_USER 
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) 
ON DELETE CASCADE;

-- 4. INSERCIÓN DE REGISTROS DE PRUEBA
INSERT INTO USERS VALUES ('usr-0001', 'Carlos Mendoza', 'carlos.mendoza@email.com', 'CLIENT');
INSERT INTO USERS_PRODUCTS VALUES ('rel-0001', 'usr-0001', '3d703247-54bc-47ef-a69d-7531a638022e', NOW()); 
INSERT INTO USERS_PRODUCTS VALUES ('rel-0002', 'usr-0001', '9fba7c1b-5972-4309-88ce-4a9ead7995fa', NOW()); 

INSERT INTO USERS VALUES ('usr-0002', 'Ana Gomez', 'ana.gomez@email.com', 'VIP');
INSERT INTO USERS_PRODUCTS VALUES ('rel-0003', 'usr-0002', '5b5d4b20-d339-4f3d-9695-92036177078b', NOW()); 

INSERT INTO USERS VALUES ('usr-0003', 'Soporte Tecnico', 'admin@products.com', 'ADMIN');

-- 5. ASIGNACIÓN DE PERMISOS
GRANT ALL PRIVILEGES ON usersdb.* TO 'users'@'%';
FLUSH PRIVILEGES;

-- 6. PROCEDIMIENTO ALMACENADO LOCAL
DELIMITER //

CREATE PROCEDURE sp_obtener_metricas_usuario(
    IN p_user_id VARCHAR(512), 
    OUT p_total_productos INT
)
BEGIN
    SELECT COUNT(*) 
    INTO p_total_productos
    FROM USERS_PRODUCTS 
    WHERE USER_ID = p_user_id;
END //

DELIMITER ;
