server:
  port: ${CONFIG_SERVER_PORT:9999}

spring:
  application:
    name: config-server
  profiles:
    active: native # 🚀 Activa el modo de lectura del sistema de archivos local
  cloud:
    config:
      server:
        native:
          # Busca los archivos .yaml de los microservicios en esta ruta del Classpath
          search-locations: classpath:/shared/{application}
